name: Build & Release

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04
          - windows-latest
        python-version:
          - "3.13"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Qt dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 mesa-utils libxcb-xinerama0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xkb1 libxkbcommon-x11-0 libxcb-cursor0

      - name: Build application with PyInstaller
        run: pyinstaller main.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NeuroSongSpider-${{ runner.os }}
          path: dist/
